### ISSUE TITLE
Adding Licence in the repo

### ISSUE THREAD

**Issue by Rajjat** [slzhou-xy/HREP#2]
Could you please add licence to your repository so that I can use your preprocessed  data?

**Comment by slzhou-xy** [comment]
Done!

**Comment by Rajjat** [comment]
Thanks for adding the license and your quick response. I have a quick query. Is the decision for license (GNU GPL) was your choice-based or random? Because GPL license come under copyleft license and if I used your preprocessed GitHub data, I have to make our code and data under GPL license.  I don't want to make the license of my repo under GPL license. I want to make my repo under MIT-license. Please let me know.  Thanks again.

**Comment by slzhou-xy** [comment]
Yes,&nbsp;I&nbsp;randomly&nbsp;select&nbsp;one,&nbsp;and&nbsp;I&nbsp;have&nbsp;changed&nbsp;it&nbsp;to&nbsp;MIT.


---Original---
From: &quot;Rajjat ***@***.***&gt;
Date: Sun, Feb 18, 2024 18:15 PM
To: ***@***.***&gt;;
Cc: &quot;Thring ***@***.******@***.***&gt;;
Subject: Re: [slzhou-xy/HREP] Adding Licence in the repo (Issue #2)




 
Thanks for adding the license and your quick response. I have a quick query. Is the decision for license (GNU GPL) was your choice-based or random? Because GPL license come under copyleft license and if I used your preprocessed GitHub data, I have to make our code and data under GPL license.  I don't want to make the license of my repo under GPL license. I want to make my repo under MIT-license. Please let me know.  Thanks again.
 
&mdash;

**Comment by slzhou-xy** [comment]
Yes, I randomly select one, and I have changed it to MIT.

**Comment by Rajjat** [comment]
Thank you so much again!
